name: Build

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install tools
      run: npm install --location=global bslint typescript

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Lint Types
      run: npm run lint-types

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test

